#+LATEX_HEADER: \usepackage{geometry}\geometry{a4paper,left=20mm,right=20mm,top=20mm,bottom=30mm}
#+LATEX_HEADER: \usepackage{mathtools} \usepackage{tikz}


#+OPTIONS: toc:nil
#+OPTIONS: num:nil
#+OPTIONS: date:nil


#+begin_export latex


\textbf{Teorema} de structură a multimilor deschise din $\mathbb{R}$
\vspace{7pt}

Orice mulțime deschisă se poate scrie ca o reuniune de sfere deschise cel mult numărabilă.

\vspace{7pt}
\textbf{Demonstrație:}
\vspace{7pt}

Fie $(\mathbb{R}, |\cdot|)$, $M \in \tau_o $.

Știm:

$| \mathbb{Q} | = | \mathbb{Q}^n | =\aleph_0, \forall n \in \mathbb{N}$\ \ \ (1)

$\forall x, y \in \mathbb{R},$ cu $x < y, \exists\ q \in \mathbb{Q}$ a.î. $x < q < y.$ (Densitatea lui $\mathbb{Q}$ în $\mathbb{R}$) \ \ \ (2)

\vspace{7pt}


Fie $F = \left\{ (x', r') \in  \mathbb{Q} \times \mathbb{Q}\ \middle|\ \exists r \in (0, \infty),\ x \in \mathbb{R} \text{ a.î. }
S(x', r') \subseteq S(x, r) \subseteq M \right\} \subseteq \mathbb{Q} \times \mathbb{Q}$.

Fie $N = \bigcup\limits_{p \in F} S(p)$.

\vspace{7pt}
Arătăm că $N \subseteq M$ (*):

Fie $(x', r') \in F$.

$(x', r') \in F \implies \exists r \in (0, \infty),\ x \in \mathbb{R} \text{ a.î. } S(x', r') \subseteq S(x, r) \subseteq M \implies S(x', r') \subseteq M$.

Cum $N = \bigcup\limits_{p \in F} S(p) \implies N \subseteq M$.


\vspace{7pt}
Arătăm că $M \subseteq N$ (**).

Presupunem prin reducere la absurd că $\exists x \in M \text{ a.î. } x \notin N \iff  \forall (x', r') \in F,\ x \notin S(x', r').$

$\begin{rcases}
M \in \tau_o \\
x \in M
\end{rcases}
\implies \exists r \in (0, \infty)$ a.î. $S(x, r) \subseteq M$.

Fie:

$\varepsilon \in \left(0,\ \frac{r}{2}\right)$;

$x' \in \mathbb{Q}  \text{ a.î. } x - \varepsilon \le x' \le x + \varepsilon$ (există din (2));

$r' \in \mathbb{Q}  \text{ a.î. } \varepsilon \le r' \le r-\varepsilon$.

\usetikzlibrary{arrows}
\begin{document}
\begin{tikzpicture}
\draw[latex-latex] (-7,0) -- (7,0) ; %edit here for the axis
\foreach \x in {-6, -5, -2, -1, 0, 2, 3, 6} % edit here for the vertical lines
\draw[shift={(\x,0)},color=black] (0pt,3pt) -- (0pt,-3pt);

\draw[shift={(-1,0)},color=black, thick] (0pt,4pt) -- (0pt,-4pt);
\draw[shift={(0,0)},color=black, very thick] (0pt,5pt) -- (0pt,-5pt);


%\foreach \x in {-6, -5, -2, -1, 0, 2, 3, 6} % edit here for the vertical lines
\draw[shift={(-6,0)},color=black] (0pt,0pt) -- (0pt,-3pt) node[below] {$x-r$};
\draw[shift={(-5,0)},color=black] (0pt,0pt) -- (0pt,3pt)  node[above] {$x'-r'$};
\draw[shift={(-2,0)},color=black] (0pt,0pt) -- (0pt,-3pt) node[below] {$x-\varepsilon$};
\draw[shift={(-1,0)},color=black] (0pt,0pt) -- (0pt,3pt) node[above] {$x'$};
\draw[shift={(0,0)},color=black] (0pt,0pt) -- (0pt,-3pt) node[below] {$x$};
\draw[shift={(2,0)},color=black] (0pt,0pt) -- (0pt,-3pt) node[below] {$x+\varepsilon$};
\draw[shift={(3,0)},color=black] (0pt,0pt) -- (0pt,3pt)  node[above] {$x'+r'$};
\draw[shift={(6,0)},color=black] (0pt,0pt) -- (0pt,-3pt) node[below] {$x-r$};


%\draw[ultra thick, black] (-6,0) -- (6,0);
\draw[(-), very thick, black] (-6,0) -- (6,0);
\draw[-, ultra thick, black] (-6,0) -- (6,0);
%\draw[thick, red] (-5,0) -- (3,0);
\draw[(-), semithick, red] (-5,0) -- (3,0);
\end{tikzpicture}

Arătăm că $S(x', r') \subseteq N$ sau, echivalent, $S(x', r') \subseteq S(x, r)$.

Fie $y \in S(x', r') = (x'-r',x'+r')$.

Demonstrăm că $y \in S(x, r)$.
\vspace{7}

$\varepsilon < r'< r - \varepsilon < r \implies 
    r' < r -\varepsilon \iff r' + \varepsilon < r$ \ \ \ (3)

$x - \varepsilon < x' < x + \varepsilon$ \ \ \  (4)

$y \in (x'-r', x'+r') \iff x'-r' < y < x' + r' \iff$

$
\iff
\begin{cases}
    y < x'+r' \xRightarrow{(4)} y < x+\varepsilon +r' \implies  y < x+ (\varepsilon +r') \xRightarrow{(3)}  y < x+r & (5)\\  
    x'-r'< y \xRightarrow{(4)} x-\varepsilon-r' < y \implies x-(\varepsilon+r') < y  \xRightarrow{(3)} x-r < y & (6)
  \end{cases}$

Din (5) și (6) $\implies x-r < y < x+r \iff |y-x| < r \iff y \in S(x, r) \iff S(x', r') \subseteq S(x, r)$.

Deci $S(x', r') \subseteq N$.

\vspace{7}
Arătăm că $x \in S(x', r').$

$x - \varepsilon < x' < x + \varepsilon \ \ \ \iff$
$ -\varepsilon < x' - x < \varepsilon \iff |x'-x| < \varepsilon$
$\implies d(x', x) < \varepsilon \stackrel{(3)}{<} r' \implies x \in S(x', r')$




Dar $S(x', r') \subseteq N$, deci $x \in N$. Contradicție. 

Deci presupunerea făcută este falsă, adică $\forall x \in M,\ \exists (x', r') \in F \text{ a.î. } x \in S(x', r') \iff $

$\iff x \in N \iff M \subseteq N$.

Din (*) și (**) $\implies N = M$

\vspace{7}
$
\begin{rcases}
$F \subseteq \mathbb{Q} \times \mathbb{Q} \implies |F| \le | \mathbb{Q} \times \mathbb{Q} | = \aleph_0$\\
$N = \bigcup\limits_{(x, r) \in F} S(x, r)$
\end{rcases} \Rightarrow N$ este o reuniune cel mult numărabilă de sfere deschise.


În concluzie am scris $M$ ca o reuniune cel mult numărabilă de sfere deschise. 
%\vspace{7}
#+end_export
